### ISSUE TITLE
plans for rails 5 support?

### ISSUE THREAD

**Issue by nurey** [zoocasa/activerecord-postgresql-extensions#9]
Any plans to support rails 5.x?

**Comment by dark-panda** [comment]
No promises but I was actually doing some work on this today. Some of the functionality has already been implemented in ActiveRecord vanilla (references, foreign keys, expressions on default values) in which case I'll remove those bits and defer to the AR implementation, so there may be a bit of a migration path required. At any rate, yes, there are "plans" on Rails 5.x support.

**Comment by nurey** [comment]
Sounds great! 🕺 👍

**Comment by rahul8sharma** [comment]
Are you planning to add a support for rails 5 or Can you please provide an alternative to it. Actually, we are upgrading our site form rails 3 to 5. Please help.
